apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exercise-tracker
  description: An application for tracking and analyzing workout exercises with AI coaching
  annotations:
    github.com/project-slug: upendrasahu/exercise-tracker
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - flask
    - kubernetes
    - fitness
    - openai
spec:
  type: service
  lifecycle: production
  owner: user:upendrasahu
  system: fitness-platform
  dependsOn:
    - resource:exercise-tracker-db
    - component:exercise-tracker-coach

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exercise-tracker-coach
  description: AI coaching service that provides personalized fitness advice
  annotations:
    github.com/project-slug: upendrasahu/exercise-tracker
  tags:
    - python
    - flask
    - openai
    - ai
spec:
  type: service
  lifecycle: production
  owner: user:upendrasahu
  system: fitness-platform
  dependsOn:
    - resource:exercise-tracker-db

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: exercise-tracker-db
  description: SQLite database for the Exercise Tracker application
  annotations:
    backstage.io/managed-by: exercise-tracker
  tags:
    - sqlite
    - database
spec:
  type: database
  owner: user:upendrasahu
  system: fitness-platform

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fitness-platform
  description: A platform for fitness tracking and AI coaching
spec:
  owner: user:upendrasahu
  domain: fitness