apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exercise-tracker
  description: An application for tracking and analyzing workout exercises with AI coaching
  annotations:
    github.com/project-slug: upendrasahu/exercise-tracker
    backstage.io/techdocs-ref: dir:.
    backstage.io/view-url: https://github.com/upendrasahu/exercise-tracker/tree/main
    backstage.io/edit-url: https://github.com/upendrasahu/exercise-tracker/edit/main
    backstage.io/source-location: url:https://github.com/upendrasahu/exercise-tracker
  tags:
    - python
    - flask
    - kubernetes
    - fitness
    - openai
  links:
    - url: https://github.com/upendrasahu/exercise-tracker
      title: GitHub Repository
      icon: github
    - url: https://github.com/upendrasahu/exercise-tracker/issues
      title: Issues
      icon: github
spec:
  type: service
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  dependsOn:
    - resource:exercise-tracker-db
    - component:exercise-tracker-coach

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exercise-tracker-coach
  description: AI coaching service that provides personalized fitness advice
  annotations:
    github.com/project-slug: upendrasahu/exercise-tracker
  tags:
    - python
    - flask
    - openai
    - ai
spec:
  type: service
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  dependsOn:
    - resource:exercise-tracker-db

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: exercise-tracker-db
  description: SQLite database for the Exercise Tracker application
  annotations:
    backstage.io/managed-by: exercise-tracker
  tags:
    - sqlite
    - database
spec:
  type: database
  owner: upendrasahu
  system: fitness-platform

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fitness-platform
  description: A platform for fitness tracking and AI coaching
spec:
  owner: upendrasahu
  domain: fitness

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: exercise-tracker-team
  description: Team responsible for the Exercise Tracker application
spec:
  type: team
  profile:
    displayName: Exercise Tracker Team
    email: team@example.com
    picture: https://example.com/teams/exercise-tracker.jpeg
  members:
    - upendrasahu
  parent: default
  children: []  # Empty array as this team doesn't have child groups

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: upendrasahu
  description: Lead Developer for Exercise Tracker
spec:
  profile:
    displayName: Upendra Sahu
    email: upendrasahu@example.com
    picture: https://example.com/staff/upendrasahu.jpeg
  memberOf: [default/exercise-tracker-team]