apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exercise-tracker
  description: An application for tracking and analyzing workout exercises with AI coaching
  annotations:
    # github.com/project-slug: upendrasahu/exercise_tracker  # Keep commented if causing issues
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/upendrasahu/exercise_tracker
    backstage.io/kubernetes-id: exercise-tracker
  tags:
    - python
    - flask
  links:
    - url: https://github.com/upendrasahu/exercise_tracker
      title: Repository
      icon: github
spec:
  type: service
  lifecycle: production # Or other appropriate lifecycle value
  owner: upendrasahu # Or the owning team/user
  system: fitness-platform
  dependsOn:
    - resource:exercise-tracker-db
    - component:exercise-tracker-coach
  providesApis:
    - exercise-tracker-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exercise-tracker-coach
  description: AI coaching service that provides personalized fitness advice
  annotations:
    # github.com/project-slug: upendrasahu/exercise_tracker # Keep commented if causing issues
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/upendrasahu/exercise_tracker
    backstage.io/kubernetes-id: exercise-tracker-coach
  tags:
    - python
    - flask
    - openai
spec:
  type: service
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  dependsOn:
    - resource:exercise-tracker-db
  providesApis:
    - coach-service-api

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: exercise-tracker-db
  description: SQLite database for the Exercise Tracker application
  annotations:
    backstage.io/managed-by: exercise-tracker
  tags:
    - sqlite
    - database
spec:
  type: database
  owner: upendrasahu
  system: fitness-platform

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fitness-platform
  description: A platform for fitness tracking and AI coaching
spec:
  owner: upendrasahu
  domain: fitness # Or other appropriate domain

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: exercise-tracker-api
  description: REST API for tracking exercises and retrieving exercise data
  annotations:
    backstage.io/source-location: url:https://github.com/upendrasahu/exercise_tracker
    backstage.io/techdocs-ref: dir:. 
  tags:
    - rest
    - fitness
  links:
    - url: https://github.com/upendrasahu/exercise_tracker/blob/main/api-specs/exercise-tracker-api.yaml
      title: API Definition
      icon: code
    - url: https://github.com/upendrasahu/exercise_tracker/blob/main/docs/api-main.md
      title: API Documentation
      icon: doc
spec:
  type: openapi
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  definition:
    $text: ./api-specs/exercise-tracker-api.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: coach-service-api
  description: REST API for AI-powered fitness coaching and personalized advice
  annotations:
    backstage.io/source-location: url:https://github.com/upendrasahu/exercise_tracker
    backstage.io/techdocs-ref: dir:.
  tags:
    - rest
    - ai
    - coaching
  links:
    - url: https://github.com/upendrasahu/exercise_tracker/blob/main/api-specs/coach-service-api.yaml
      title: API Definition
      icon: code
    - url: https://github.com/upendrasahu/exercise_tracker/blob/main/docs/api-coach.md
      title: API Documentation
      icon: doc
spec:
  type: openapi
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  definition:
    $text: ./api-specs/coach-service-api.yaml
