apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exercise-tracker
  description: An application for tracking and analyzing workout exercises with AI coaching
  annotations:
    github.com/project-slug: upendrasahu/exercise_tracker
    backstage.io/techdocs-ref: dir:.
    backstage.io/view-url: https://github.com/upendrasahu/exercise_tracker/tree/main
    backstage.io/edit-url: https://github.com/upendrasahu/exercise_tracker/edit/main
    backstage.io/source-location: url:https://github.com/upendrasahu/exercise_tracker
    github.com/actions-workflows-branch: main
    github.com/actions-workflow-enforce: "true"
  tags:
    - python
    - flask
    - kubernetes
    - fitness
    - openai
  links:
    - url: https://github.com/upendrasahu/exercise_tracker
      title: GitHub Repository
      icon: github
    - url: https://github.com/upendrasahu/exercise_tracker/issues
      title: Issues
      icon: github
    - url: https://github.com/upendrasahu/exercise_tracker/actions
      title: GitHub Workflows
      icon: github
spec:
  type: service
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  dependsOn:
    - resource:exercise-tracker-db
    - component:exercise-tracker-coach
  providesApis:
    - exercise-tracker-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: exercise-tracker-coach
  description: AI coaching service that provides personalized fitness advice
  annotations:
    github.com/project-slug: upendrasahu/exercise_tracker
    github.com/actions-workflows-branch: main
    github.com/actions-workflow-enforce: "true"
  tags:
    - python
    - flask
    - openai
    - ai
spec:
  type: service
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  dependsOn:
    - resource:exercise-tracker-db
  providesApis:
    - coach-service-api

---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: exercise-tracker-db
  description: SQLite database for the Exercise Tracker application
  annotations:
    backstage.io/managed-by: exercise-tracker
  tags:
    - sqlite
    - database
spec:
  type: database
  owner: upendrasahu
  system: fitness-platform

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: fitness-platform
  description: A platform for fitness tracking and AI coaching
spec:
  owner: upendrasahu
  domain: fitness

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: exercise-tracker-api
  description: REST API for tracking exercises and retrieving exercise data
  tags:
    - rest
    - json
    - exercise
    - python
  annotations:
    backstage.io/source-location: url:https://github.com/upendrasahu/exercise_tracker
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/upendrasahu/exercise_tracker/blob/main/docs/api-main.md
      title: API Documentation
      icon: doc
spec:
  type: openapi
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  definition:
    $text: ./api-specs/exercise-tracker-api.yaml

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: coach-service-api
  description: REST API for AI-powered fitness coaching and personalized advice
  tags:
    - rest
    - json
    - ai
    - coach
    - openai
  annotations:
    backstage.io/source-location: url:https://github.com/upendrasahu/exercise_tracker
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/upendrasahu/exercise_tracker
      title: GitHub Repository
      icon: github
    - url: https://github.com/upendrasahu/exercise_tracker/issues
      title: Issues
      icon: github
    - url: https://github.com/upendrasahu/exercise_tracker/actions
      title: GitHub Workflows
      icon: github
spec:
  type: openapi
  lifecycle: production
  owner: upendrasahu
  system: fitness-platform
  definition:
    $text: ./api-specs/coach-service-api.yaml