apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: exercise-tracker-team
  description: Team responsible for the Exercise Tracker application
spec:
  type: team
  profile:
    displayName: Exercise Tracker Team
    email: team@example.com
  members:
    - upendrasahu
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: upendrasahu
  description: Personal group for upendrasahu
spec:
  type: team
  profile:
    displayName: Upendra Sahu
    email: upendrasahu@example.com
  members:
    - upendrasahu
  children: []