{{- if .Values.coachService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: coach-service-secrets
  labels:
    {{- include "exercise-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  # This is a placeholder. In production, you should use a proper secret management system
  # like Kubernetes Secrets, Vault, or set this via CI/CD pipeline.
  openai-api-key: {{ .Values.coachService.openaiApiKey | default "" | b64enc }}
{{- end }}