apiVersion: v1
kind: Secret
metadata:
  name: exercise-tracker-secrets
  labels:
    {{- include "exercise-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  # This is a default secret key for development. In production,
  # you should provide a proper secret.
  secret-key: {{ .Values.exerciseTracker.secretKey | default "ZGV2ZWxvcG1lbnRfc2VjcmV0X2tleQ==" | quote }}